<?php

namespace App\Blendx;

class CaseMain extends Blender
{
    protected $relations = [
        'case_categories',
        'case_natures',
        'programs',
        'regions',
        'districts',
        'police_stations',
        'courts',
        'case_statuses',
        'court_orders',
        'additional_court_orders',
        'next_date_statuses',
        'lawyers',
        'case_issue_logs',
        'case_types',
        'case_proceedings',
        'billings'

    ];
    public static function store_validator($route)
    {
        $custom_validator = [
            'witness' => 'nullable',
            'case_notes'=>'required',
        ];
        $store = parent::store_validator($route);
        $finale = array_merge($store,$custom_validator);
        return $finale;

    }
//    public static function after_validator($validated, $route, $user = null)
//    {
//        $custom
//        $after =  parent::after_validator($validated, $route, $user); // TODO: Change the autogenerated stub
//    }

    public static function update_validator($route)
    {
        $custom_validator = [

        ];

        return $custom_validator;
    }
}
