<?php

namespace App\Blendx;

class DcmcMeeting extends Blender
{
    protected $relations = [
        'districts'
    ];
    public static function store_validator($route)
    {
        $custom_validator = [
            'file_name'=>'required',
        ];
        $store = parent::store_validator($route);
        $finale = array_merge($store,$custom_validator);
        return $finale;

    }
//    public static function after_validator($validated, $route, $user = null)
//    {
//        $custom
//        $after =  parent::after_validator($validated, $route, $user); // TODO: Change the autogenerated stub
//    }

    public static function update_validator($route)
    {

        $custom_validator = [
            'file_name'=>'nullable',
        ];
        $store = parent::update_validator($route);
        $finale = array_merge($store,$custom_validator);
        return $finale;
    }
}
